project:
  type: website

website:
  title: "Caleb M. Marshall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - href: code.qmd
        text: Code
    right:
      - icon: github
        href: https://github.com/caleb-m-marshall

format:
  html:
    theme: cosmo
    toc: true
